"""New Migration

Revision ID: d7e5e4f5c731
Revises: 
Create Date: 2022-11-30 22:34:27.891744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e5e4f5c731'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titatic',
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Survived', sa.String(), nullable=True),
    sa.Column('Pclass', sa.Integer(), nullable=True),
    sa.Column('Sex', sa.String(), nullable=True),
    sa.Column('Age', sa.Numeric(), nullable=True),
    sa.Column('Siblings_Spouses_Aboard', sa.Integer(), nullable=True),
    sa.Column('Parents_Children_Aboard', sa.Integer(), nullable=True),
    sa.Column('Fare', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('Name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('titatic')
    # ### end Alembic commands ###
